project_id = "uyughsvfwngfdexallmm"
[functions.visual-search]
enabled = true
verify_jwt = false
import_map = "./functions/visual-search/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/visual-search/index.ts"

[functions.be-zone-agent]
enabled = true
verify_jwt = false
import_map = "./functions/be-zone-agent/deno.json"
entrypoint = "./functions/be-zone-agent/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/visual-search/*.html" ]
